--liquibase formatted sql

CREATE TABLE if NOT EXISTS users
(
    id         INTEGER generated by default as identity primary key,
    username   CHARACTER VARYING(255) not null,
    password   CHARACTER VARYING(255) not null,
    first_name CHARACTER VARYING(255) not null,
    last_name  CHARACTER VARYING(255) not null,
    phone      CHARACTER VARYING(255) not null,
    email      CHARACTER VARYING(255) not null,
    role       CHARACTER VARYING(255) not null,
    image      CHARACTER VARYING(255)
);

CREATE TABLE if NOT EXISTS ads
(
    id          INTEGER generated by default as identity primary key,
    image       CHARACTER VARYING(255),
    price       INTEGER                not null,
    title       CHARACTER VARYING(255) not null,
    description CHARACTER VARYING(255) not null,
    user_id     INTEGER                not null,
    FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE if NOT EXISTS comments
(
    id                INTEGER generated by default as identity primary key,
    author_image      CHARACTER VARYING(255),
    author_first_name CHARACTER VARYING(255) not null,
    created_at        TIMESTAMP,
    text              CHARACTER VARYING(255) not null,
    user_id           INTEGER                not null,
    ad_id             INTEGER                not null,
    FOREIGN KEY (user_id) REFERENCES users (id),
    FOREIGN KEY (ad_id) REFERENCES ads (id)
);